spring:
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    host: localhost
    port: 6379
    timeout: 3000

  mail:
    host: smtp.gmail.com
    port: 587
    username: rememberallbystella@gmail.com
    password: kijbjegmpylwauwe
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 1800 # 30분
  refresh-token-validity-in-seconds: 1209600  # 20160분, 2주

cloud:
  aws:
    credentials:
      accessKey: AKIARYSHLBR5AX7W2VFX
      secretKey: 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
    s3:
      bucket: rememberall
      dir: user-image
    region:
      static: ap-northeast-2
    stack:
      auto: false